# Generated by Django 5.0.6 on 2024-06-26 12:28

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_pk", models.IntegerField(unique=True)),
                ("pseudonym", models.CharField(max_length=65, unique=True)),
                ("first_name", models.CharField(max_length=65)),
                ("last_name", models.CharField(max_length=65)),
                ("description", models.CharField(max_length=255, null=True)),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to=chat.models.user_image_file_path
                    ),
                ),
                ("subscribe", models.ManyToManyField(blank=True, to="chat.profile")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
