# Generated by Django 5.0.6 on 2024-06-21 17:19

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pseudonym", models.CharField(max_length=65, unique=True)),
                ("first_name", models.CharField(max_length=65)),
                ("last_name", models.CharField(max_length=65)),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to=chat.models.user_image_file_path
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pseudonym_id", models.IntegerField()),
                (
                    "my_subscribe",
                    models.ManyToManyField(related_name="subscribe", to="chat.profile"),
                ),
            ],
        ),
    ]
