# Generated by Django 5.0.6 on 2024-06-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscribe",
            field=models.ManyToManyField(blank=True, to="chat.profile"),
        ),
        migrations.AddField(
            model_name="profile",
            name="user_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Subscribe",
        ),
    ]
