# Generated by Django 5.0.6 on 2024-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_profile_subscribe_profile_user_id_delete_subscribe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_id",
            field=models.IntegerField(unique=True),
        ),
    ]
