# Generated by Django 5.0.6 on 2024-06-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_profile_user_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="subscribe",
            field=models.ManyToManyField(
                blank=True, related_name="profile", to="chat.profile"
            ),
        ),
    ]
