# Generated by Django 5.0.6 on 2024-06-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_profile_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
