# Generated by Django 5.0.6 on 2024-06-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="subscribe",
            field=models.ManyToManyField(
                blank=True, related_name="subscribe_me", to="chat.profile"
            ),
        ),
    ]
